---
name: 🐛 Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! 🐛

        **Quick check:** Has this bug been [already reported](https://github.com/haxtheweb/issues/issues)?

        **Need help or have questions?** Connect with us:
        - [Discord](https://discord.gg/EKYJAjqGhf) for community support
        - [LinkedIn](http://linkedin.com/company/haxtheweb) for updates
        - [X](https://x.com/haxtheweb) for updates

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project does this bug affect?
      options:
        - webcomponents
        - create
        - haxcms-php
        - haxcms-nodejs
        - HAX editor
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in a few sentences
      placeholder: When I do X, Y happens instead of Z
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: How to reproduce
      description: Simple steps to reproduce the issue (optional but helpful)
      placeholder: |
        1. Go to...
        2. Click...
        3. See error
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional details
      description: Browser, OS, screenshots, error messages, etc. (optional)
      placeholder: Any additional context that might help
    validations:
      required: false
