blank_issues_enabled: false
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/aCGxmRHEJP
    about: Join our Discord for questions, discussions, and community support
  - name: 👔 LinkedIn
    url: http://linkedin.com/company/haxtheweb
    about: Connect with us on LinkedIn for professional updates and networking
  - name: 📚 Documentation
    url: https://haxtheweb.org/documentation
    about: Check our comprehensive documentation for guides and tutorials
  - name: 🎮 Try HAX on hax.cloud
    url: https://hax.cloud/magicscript.html
    about: Explore and experiment with HAXcms, components and more with the magic script