---
name: ✨ Feature request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! ✨

        **Quick check:** Has this feature been [already requested](https://github.com/haxtheweb/issues/issues)?

        **Need help or want to discuss ideas?** Connect with us:
        - [Discord](https://discord.gg/EKYJAjqGhf) for community support
        - [LinkedIn](http://linkedin.com/company/haxtheweb) for updates
        - [X](https://x.com/haxtheweb) for updates

  - type: dropdown
    id: project
    attributes:
      label: Project
      description: Which project would this feature affect?
      options:
        - webcomponents (UX / frontend)
        - create (hax CLI)
        - Documentation
        - HAX editing experience
        - HAXCMS site builder
        - haxcms-php (backend)
        - haxcms-nodejs (backend)
        - Other (integrations, etc)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the feature you'd like
      placeholder: I would like HAXTheWeb to be able to...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why would this be useful?
      description: What problem would this solve or what would it help you accomplish?
      placeholder: This would help me/users to...
    validations:
      required: false
